# Alt Küme Üzerinde İşlem Yapmak

In [1]:
import numpy as np

In [3]:
a = np.random.randint(10,size = (5,5))
a

array([[1, 5, 3, 6, 1],
       [5, 0, 7, 8, 3],
       [2, 7, 6, 2, 6],
       [7, 0, 5, 5, 3],
       [7, 9, 8, 4, 2]])

In [4]:
alt_a = a[0:3, 0:2]
alt_a

array([[1, 5],
       [5, 0],
       [2, 7]])

In [5]:
alt_a[0,0] = 99999
alt_a[1,1] = 888

In [6]:
alt_a

array([[99999,     5],
       [    5,   888],
       [    2,     7]])

In [7]:
a

array([[99999,     5,     3,     6,     1],
       [    5,   888,     7,     8,     3],
       [    2,     7,     6,     2,     6],
       [    7,     0,     5,     5,     3],
       [    7,     9,     8,     4,     2]])

In [8]:
m = np.random.randint(10,size = (5,5))
m

array([[7, 3, 2, 3, 0],
       [1, 9, 3, 4, 2],
       [0, 4, 3, 2, 6],
       [4, 0, 7, 5, 1],
       [2, 5, 9, 7, 6]])

In [13]:
alt_b = m[0:3, 0:2].copy()
alt_b

array([[7, 3],
       [1, 9],
       [0, 4]])

In [14]:
alt_b[0,0] = 9999
alt_b

array([[9999,    3],
       [   1,    9],
       [   0,    4]])

In [16]:
m


array([[7, 3, 2, 3, 0],
       [1, 9, 3, 4, 2],
       [0, 4, 3, 2, 6],
       [4, 0, 7, 5, 1],
       [2, 5, 9, 7, 6]])

In [19]:
n = alt_b*3
n

array([[29997,     9],
       [    3,    27],
       [    0,    12]])

# Array Concatenation (Birleştirme)

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [13]:
t = np.concatenate([x,y])
t

array([1, 2, 3, 4, 5, 6])

In [7]:
z = np.array([7,8,9])

In [11]:
np.concatenate([t,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#iki boyutlularda nasıl yapılır?

In [14]:
a = np.array([[1,2,3],
              [4,5,6]])

#satır formunda birleştirme

In [17]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

#sütun formunda birleştirme

In [18]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array Sorting (sıralama)

In [1]:
import numpy as np

In [2]:
v = np.array([2,3,5,4,1])

In [3]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [4]:
v

array([2, 3, 5, 4, 1])

In [5]:
v.sort()

In [6]:
v

array([1, 2, 3, 4, 5])

# İki Boyutlu array sıralama

In [11]:
m = np.random.normal(20,5, (3,3))
m

array([[15.99583653, 20.03335879, 20.57036848],
       [15.54939612, 26.42257434, 23.20909087],
       [16.64878592, 15.52613906, 18.20811064]])

In [13]:
np.sort(m, axis=1)

array([[15.99583653, 20.03335879, 20.57036848],
       [15.54939612, 23.20909087, 26.42257434],
       [15.52613906, 16.64878592, 18.20811064]])

In [14]:
np.sort(m, axis=0)

array([[15.54939612, 15.52613906, 18.20811064],
       [15.99583653, 20.03335879, 20.57036848],
       [16.64878592, 26.42257434, 23.20909087]])

# Array Splitting (Ayırma)

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,99,99,3,2,1])

In [3]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [7]:
a,b,c = np.split(x, [3,5])

In [8]:
a

array([1, 2, 3])

In [9]:
b

array([99, 99])

In [10]:
c

array([3, 2, 1])

#İki boyutlu arrayları ayırma

In [16]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [24]:
eren, demo = np.vsplit(m,[2])

In [26]:
eren

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [27]:
demo

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

# FANCY INDEX İŞLEMLERİ

In [1]:
import numpy as np

In [2]:
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [3]:
v[1]

3

In [4]:
v[3]

9

In [5]:
v[5]

15

In [6]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [7]:
al_getir = [1,3,5]

In [8]:
v[al_getir]

array([ 3,  9, 15])

# iki boyutla fancy

In [11]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
satir = np.array((0,1))
sutun = np.array((1,2))

In [13]:
m[satir, sutun]

array([1, 5])

# basit index ile fancy index

In [14]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
m[0,[1,2]]

array([1, 2])

# slice ile fancy

In [16]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

## Numpy İki Bilinmeyenli Denklem Çözümü

In [1]:
import numpy as np

In [3]:
a = np.array([[5,1], [1,3]])
b = np.array([12,10])

In [22]:
a

array([[5, 1],
       [1, 3]])

In [23]:
b

array([12, 10])

In [24]:
x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])

# Koşullu eleman işlemleri

In [59]:
import numpy as np

v = np.array([1,2,3,4,5])

In [60]:
v > 5

array([False, False, False, False, False])

In [61]:
v < 5

array([ True,  True,  True,  True, False])

In [63]:
v[v <5]

array([1, 2, 3, 4])

In [64]:
v[v<=3]

array([1, 2, 3])

In [65]:
v[v!=3]

array([1, 2, 4, 5])

In [66]:
v

array([1, 2, 3, 4, 5])

In [67]:
v*2

array([ 2,  4,  6,  8, 10])

In [68]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [69]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [70]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

## Mathematical Calculations

In [2]:
import numpy as np


In [4]:
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [5]:
v -1

array([0, 1, 2, 3, 4])

In [6]:
v *5

array([ 5, 10, 15, 20, 25])

In [7]:
v / 5


array([0.2, 0.4, 0.6, 0.8, 1. ])

In [8]:
#ufunc


In [9]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [10]:
np.add(v,4)

array([5, 6, 7, 8, 9])

In [11]:
np.multiply(v,3)

array([ 3,  6,  9, 12, 15])

In [12]:
np.divide(v,3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [13]:
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [15]:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [16]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [17]:
np.absolute(np.array([-3]))

array([3])

In [18]:
np.sin(360)

0.9589157234143065

In [19]:
v = np.array([ 1,2,3])

In [20]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [21]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [24]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [25]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\ereno\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\ereno\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >

## istatistiksel hesaplamalar

In [27]:
np.mean(v,axis=0)

2.0

In [28]:
v.sum()

6

In [29]:
v.min()

1

In [ ]:
np.mean(arr,axis=0) | Returns mean along specific axis
arr.sum() | Returns sum of arr
arr.min() | Returns minimum value of arr
arr.max(axis=0) | Returns maximum value of specific axis
np.var(arr) | Returns the variance of array
np.std(arr,axis=1) | Returns the standard deviation of specific axis
arr.corrcoef() | Returns correlation coefficient of array

# RANDINT


* **ndim:**   dimension count 
* **shape:**  dimension information
* **size:**   total number of elements
* **dtype:**  array data type

In [1]:
import numpy as np

In [3]:
np.random.randint(10, size=10)

array([7, 3, 6, 9, 0, 2, 6, 9, 5, 5])

In [5]:
a = np.random.randint(10, size=10)
a.ndim

1

In [8]:
a = np.random.randint(10, size=10)
a.shape

(10,)

In [9]:
a = np.random.randint(10, size=10)
a.size

10

In [10]:
a = np.random.randint(10, size=10)
a.dtype

dtype('int32')

In [12]:
b = np.random.randint(10, size = (3,5))

In [13]:
b

array([[5, 1, 7, 0, 5],
       [5, 3, 2, 6, 3],
       [6, 6, 4, 7, 1]])

In [14]:
b.ndim

2

In [15]:
b.shape

(3, 5)

In [16]:
b.size

15

In [18]:
b.dtype

dtype('int32')

# RESHAPING

In [12]:
import numpy as np

In [13]:
np.arange(1,10)

array([3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a.ndim

1

In [17]:
b = a.reshape((1,9))

In [18]:
b.ndim

2