# RESHAPING

In [12]:
import numpy as np

In [13]:
np.arange(1,10)

array([3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a.ndim

1

In [17]:
b = a.reshape((1,9))

In [18]:
b.ndim

2