# Array Sorting (sıralama)

In [1]:
import numpy as np

In [2]:
v = np.array([2,3,5,4,1])

In [3]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [4]:
v

array([2, 3, 5, 4, 1])

In [5]:
v.sort()

In [6]:
v

array([1, 2, 3, 4, 5])

# İki Boyutlu array sıralama

In [11]:
m = np.random.normal(20,5, (3,3))
m

array([[15.99583653, 20.03335879, 20.57036848],
       [15.54939612, 26.42257434, 23.20909087],
       [16.64878592, 15.52613906, 18.20811064]])

In [13]:
np.sort(m, axis=1)

array([[15.99583653, 20.03335879, 20.57036848],
       [15.54939612, 23.20909087, 26.42257434],
       [15.52613906, 16.64878592, 18.20811064]])

In [14]:
np.sort(m, axis=0)

array([[15.54939612, 15.52613906, 18.20811064],
       [15.99583653, 20.03335879, 20.57036848],
       [16.64878592, 26.42257434, 23.20909087]])