# Array Concatenation (Birleştirme)

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [13]:
t = np.concatenate([x,y])
t

array([1, 2, 3, 4, 5, 6])

In [7]:
z = np.array([7,8,9])

In [11]:
np.concatenate([t,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#iki boyutlularda nasıl yapılır?

In [14]:
a = np.array([[1,2,3],
              [4,5,6]])

#satır formunda birleştirme

In [17]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

#sütun formunda birleştirme

In [18]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])