# FANCY INDEX İŞLEMLERİ

In [1]:
import numpy as np

In [2]:
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [3]:
v[1]

3

In [4]:
v[3]

9

In [5]:
v[5]

15

In [6]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [7]:
al_getir = [1,3,5]

In [8]:
v[al_getir]

array([ 3,  9, 15])

# iki boyutla fancy

In [11]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
satir = np.array((0,1))
sutun = np.array((1,2))

In [13]:
m[satir, sutun]

array([1, 5])

# basit index ile fancy index

In [14]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
m[0,[1,2]]

array([1, 2])

# slice ile fancy

In [16]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])