## Numpy İki Bilinmeyenli Denklem Çözümü

In [19]:
import numpy as np

In [20]:
5 * x0 + x1 =12
xo + 3 * x1  =10


SyntaxError: cannot assign to operator (<ipython-input-20-92a6ac492cab>, line 1)

In [21]:
a = np.array([[5,1], [1,3]])
b = np.array([12,10])

In [22]:
a

array([[5, 1],
       [1, 3]])

In [23]:
b

array([12, 10])

In [24]:
x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])